# Generated by Django 6.0.8 on 2026-10-02 19:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(unique=True)),
                ('provider', models.CharField(max_length=32)),
                ('from_email', models.EmailField(max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=128)),
                ('sending_domain', models.CharField(blank=True, max_length=255)),
                ('bulk_from_email', models.EmailField(blank=True, max_length=254)),
                ('credentials_ciphertext', models.TextField(blank=True)),
                ('credentials_hint', models.CharField(blank=True, max_length=32)),
                ('webhook_ciphertext', models.TextField(blank=True)),
                ('webhook_hint', models.CharField(blank=True, max_length=32)),
                ('configured', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LaneState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lane', models.CharField(max_length=32, unique=True)),
                ('paused', models.BooleanField(default=False)),
                ('paused_at', models.DateTimeField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('service', models.CharField(max_length=64)),
                ('template_key', models.CharField(max_length=128)),
                ('template_version', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=8)),
                ('lane', models.CharField(max_length=32)),
                ('status', models.CharField(db_index=True, default='queued', max_length=32)),
                ('to_email', models.EmailField(max_length=254)),
                ('to_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('email_hmac', models.CharField(db_index=True, max_length=64)),
                ('variables_ciphertext', models.TextField(blank=True)),
                ('provider', models.CharField(blank=True, max_length=32)),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=128)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('smtp_failover_used', models.BooleanField(default=False)),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('event_type', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=64)),
                ('name', models.CharField(blank=True, max_length=128)),
                ('key_prefix', models.CharField(db_index=True, max_length=20)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('allowed_lanes', models.JSONField(default=list)),
                ('allowed_template_prefixes', models.JSONField(default=list)),
                ('allowed_company_ids', models.JSONField(blank=True, null=True)),
                ('callback_url', models.URLField(blank=True)),
                ('callback_secret_ciphertext', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['service', 'id'],
            },
        ),
        migrations.CreateModel(
            name='EmailRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(blank=True, null=True)),
                ('service', models.CharField(max_length=64)),
                ('event_type', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=False)),
                ('template_key', models.CharField(max_length=128)),
                ('language', models.CharField(blank=True, max_length=8)),
                ('recipient_mode', models.CharField(default='hints', max_length=16)),
                ('static_recipients', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company_id', 'event_type'), name='uniq_company_email_rule'), models.UniqueConstraint(condition=models.Q(('company_id__isnull', True)), fields=('event_type',), name='uniq_platform_email_rule')],
            },
        ),
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_key', models.CharField(max_length=128)),
                ('company_id', models.PositiveIntegerField(blank=True, null=True)),
                ('language', models.CharField(max_length=8)),
                ('active_version', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('template_key', 'company_id', 'language'), name='uniq_template_company_lang'), models.UniqueConstraint(condition=models.Q(('company_id__isnull', True)), fields=('template_key', 'language'), name='uniq_platform_template_lang')],
            },
        ),
        migrations.CreateModel(
            name='MessageEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=32)),
                ('occurred_at', models.DateTimeField()),
                ('provider_event_id', models.CharField(blank=True, max_length=128, null=True, unique=True)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='email.message')),
            ],
            options={
                'ordering': ['occurred_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SendRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=64)),
                ('company_id', models.PositiveIntegerField()),
                ('idempotency_key', models.CharField(max_length=200)),
                ('payload_hash', models.CharField(max_length=64)),
                ('response_status', models.PositiveIntegerField()),
                ('response_body', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('service', 'company_id', 'idempotency_key'), name='uniq_send_idempotency')],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='send_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email.sendrequest'),
        ),
        migrations.CreateModel(
            name='Suppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(blank=True, null=True)),
                ('email_hmac', models.CharField(max_length=64)),
                ('email_masked', models.CharField(max_length=255)),
                ('reason', models.CharField(max_length=32)),
                ('lanes', models.JSONField(blank=True, default=list)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['email_hmac', 'company_id'], name='email_suppression_lookup_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('state', models.CharField(default='draft', max_length=16)),
                ('subject', models.CharField(max_length=255)),
                ('preheader', models.CharField(blank=True, max_length=255)),
                ('document', models.JSONField(default=dict)),
                ('html', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('theme_name', models.CharField(default='shellui', max_length=64)),
                ('theme_palette', models.JSONField(blank=True, default=dict)),
                ('renderer_version', models.CharField(blank=True, max_length=32)),
                ('checksum', models.CharField(blank=True, max_length=64)),
                ('created_by_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='email.emailtemplate')),
            ],
            options={
                'ordering': ['template_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Unsubscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField()),
                ('email_hmac', models.CharField(max_length=64)),
                ('category', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('company_id', 'email_hmac', 'category'), name='uniq_unsubscribe')],
            },
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['lane', 'status', 'next_attempt_at'], name='email_msg_lane_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['company_id', 'accepted_at'], name='email_msg_company_day_idx'),
        ),
        migrations.AddConstraint(
            model_name='templateversion',
            constraint=models.UniqueConstraint(fields=('template', 'number'), name='uniq_template_version_number'),
        ),
    ]
