# Generated by Django 6.0.8 on 2026-10-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0005_library_templates'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailrule',
            options={'ordering': ['event_type', 'created_at', 'id']},
        ),
        migrations.AddField(
            model_name='templateversion',
            name='rendered',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='templateversion',
            name='translations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
