# Generated by Django 6.0.8 on 2026-10-05 08:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0008_hosted_fonts'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='kind',
            field=models.CharField(default='event', max_length=16),
        ),
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('audience', models.JSONField(blank=True, default=dict)),
                ('state', models.CharField(default='draft', max_length=16)),
                ('delivery', models.CharField(blank=True, max_length=16)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('template_version', models.PositiveIntegerField(blank=True, null=True)),
                ('resend_ids', models.JSONField(blank=True, default=dict)),
                ('resend_lookup', models.CharField(blank=True, db_index=True, max_length=512)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('created_by_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('template', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='broadcast', to='email.emailtemplate')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_ciphertext', models.TextField(blank=True)),
                ('email_hmac', models.CharField(max_length=64)),
                ('language', models.CharField(max_length=8)),
                ('status', models.CharField(default='pending', max_length=24)),
                ('broadcast', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='email.broadcast')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='email.message')),
            ],
            options={
                'indexes': [models.Index(fields=['broadcast', 'status'], name='email_bcast_recipient_idx')],
                'constraints': [models.UniqueConstraint(fields=('broadcast', 'email_hmac'), name='uniq_broadcast_recipient')],
            },
        ),
    ]
