# Generated by Django 6.0.8 on 2026-10-05 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email', '0009_broadcasts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='kind',
            field=models.CharField(default='event', max_length=32),
        ),
        migrations.CreateModel(
            name='NewsletterList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('public_key', models.CharField(max_length=40, unique=True)),
                ('default_language', models.CharField(default='en', max_length=8)),
                ('allowed_origins', models.JSONField(blank=True, default=list)),
                ('confirmed_redirect_url', models.CharField(blank=True, max_length=500)),
                ('turnstile_site_key', models.CharField(blank=True, max_length=100)),
                ('turnstile_secret_ciphertext', models.TextField(blank=True)),
                ('created_by_user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmation_template', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='newsletter', to='email.emailtemplate')),
            ],
            options={
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_ciphertext', models.TextField(blank=True)),
                ('email_hmac', models.CharField(max_length=64)),
                ('email_masked', models.CharField(max_length=255)),
                ('first_name', models.CharField(blank=True, max_length=150)),
                ('language', models.CharField(max_length=8)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('source', models.CharField(default='form', max_length=16)),
                ('confirm_token_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('confirm_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='email.newsletterlist')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['list', 'status'], name='email_nl_subscriber_idx')],
                'constraints': [models.UniqueConstraint(fields=('list', 'email_hmac'), name='uniq_newsletter_subscriber')],
            },
        ),
    ]
