# Generated by Django 6.0.8 on 2026-10-02 19:45

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('event_type', models.CharField(max_length=128)),
                ('enabled', models.BooleanField(default=True)),
                ('action_kind', models.CharField(choices=[('webhook', 'Webhook')], default='webhook', max_length=16)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['company_id', 'event_type', 'name'],
                'indexes': [models.Index(fields=['company_id', 'event_type', 'enabled'], name='actions_act_company_2491c6_idx')],
            },
        ),
        migrations.CreateModel(
            name='ActionOutbox',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_id', models.PositiveIntegerField(db_index=True)),
                ('event_type', models.CharField(max_length=128)),
                ('envelope', models.JSONField()),
                ('status', models.CharField(db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.CharField(blank=True, max_length=64)),
                ('webhook_id', models.CharField(max_length=64, unique=True)),
                ('target_url', models.URLField(blank=True)),
                ('callback_service', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('action_rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outbox_rows', to='actions.actionrule')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=16)),
                ('http_status', models.PositiveIntegerField(blank=True, null=True)),
                ('error_code', models.CharField(blank=True, max_length=64)),
                ('attempt_number', models.PositiveIntegerField()),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('outbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='actions.actionoutbox')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('company_id', models.PositiveIntegerField()),
                ('user_id', models.PositiveIntegerField(blank=True, null=True)),
                ('event_type', models.CharField(max_length=128)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['company_id', '-created_at'], name='actions_eventlog_company_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='actionoutbox',
            index=models.Index(fields=['status', 'next_attempt_at'], name='actions_act_status_dbeabd_idx'),
        ),
    ]
