# Generated by Django 6.0.8 on 2026-10-06 19:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobState',
            fields=[
                ('job', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('last_skipped_at', models.DateTimeField(blank=True, null=True)),
                ('last_duration_ms', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scheduled job state',
                'verbose_name_plural': 'Scheduled job states',
            },
        ),
        migrations.AddField(
            model_name='deliveryattempt',
            name='scheduled_job_run_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='company_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ScheduledJobCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('value', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Scheduled job counter',
                'verbose_name_plural': 'Scheduled job counters',
                'constraints': [models.UniqueConstraint(fields=('job', 'name'), name='actions_sjcounter_job_name_uniq')],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job', models.CharField(max_length=64)),
                ('trigger', models.CharField(choices=[('celery', 'Celery beat'), ('command', 'Management command')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('skipped_locked', 'Skipped (lock held)')], default='running', max_length=16)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('error_key', models.CharField(blank=True, max_length=32)),
                ('error_class', models.CharField(blank=True, max_length=128)),
                ('error_message', models.CharField(blank=True, max_length=300)),
                ('host', models.CharField(blank=True, max_length=128)),
                ('event_log_id', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scheduled job run',
                'verbose_name_plural': 'Scheduled job runs',
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['job', '-started_at'], name='actions_sjrun_job_idx'), models.Index(fields=['started_at'], name='actions_sjrun_started_idx')],
            },
        ),
    ]
