from django.urls import path

from apps.email.views import (
    BroadcastDetailView,
    BroadcastListView,
    BroadcastPreviewView,
    BroadcastSendView,
    CatalogView,
    EventIngestView,
    HealthView,
    LanePauseView,
    LibraryDetailView,
    LibraryListView,
    MessageCancelView,
    MessageDetailView,
    MessageListView,
    MetricsView,
    PrivacyEraseView,
    ProviderTestSendView,
    ProviderView,
    ProviderWebhookView,
    RuleDetailView,
    RuleListView,
    SendBatchView,
    SendView,
    ServiceClientListView,
    StatsView,
    SuppressionDetailView,
    SuppressionListView,
    TemplateDetailView,
    TemplateListView,
    TemplatePublishView,
    TemplateTestSendView,
    TemplateVersionDetailView,
    TemplateVersionListView,
)

urlpatterns = [
    path('health', HealthView.as_view(), name='email-health'),
    path('metrics', MetricsView.as_view(), name='email-metrics'),
    path('send', SendView.as_view(), name='email-send'),
    path('send/batch', SendBatchView.as_view(), name='email-send-batch'),
    path('events', EventIngestView.as_view(), name='email-events'),
    path('messages', MessageListView.as_view(), name='email-messages'),
    path('messages/<str:message_id>', MessageDetailView.as_view(), name='email-message-detail'),
    path('messages/<str:message_id>/cancel', MessageCancelView.as_view(), name='email-message-cancel'),
    path('catalog', CatalogView.as_view(), name='email-catalog'),
    path('library', LibraryListView.as_view(), name='email-library'),
    path('library/<int:library_id>', LibraryDetailView.as_view(), name='email-library-detail'),
    path('templates', TemplateListView.as_view(), name='email-templates'),
    path('templates/<int:template_id>', TemplateDetailView.as_view(), name='email-template-detail'),
    path('templates/<int:template_id>/versions', TemplateVersionListView.as_view(), name='email-template-versions'),
    path(
        'templates/<int:template_id>/versions/<int:number>',
        TemplateVersionDetailView.as_view(),
        name='email-template-version',
    ),
    path(
        'templates/<int:template_id>/versions/<int:number>/publish',
        TemplatePublishView.as_view(),
        name='email-template-publish',
    ),
    path('templates/<int:template_id>/send-test', TemplateTestSendView.as_view(), name='email-template-test-send'),
    path('broadcasts', BroadcastListView.as_view(), name='email-broadcasts'),
    path('broadcasts/<int:broadcast_id>', BroadcastDetailView.as_view(), name='email-broadcast-detail'),
    path('broadcasts/<int:broadcast_id>/preview', BroadcastPreviewView.as_view(), name='email-broadcast-preview'),
    path('broadcasts/<int:broadcast_id>/send', BroadcastSendView.as_view(), name='email-broadcast-send'),
    path('rules', RuleListView.as_view(), name='email-rules'),
    path('rules/<int:rule_id>', RuleDetailView.as_view(), name='email-rule-detail'),
    path('provider', ProviderView.as_view(), name='email-provider'),
    path('provider/test-send', ProviderTestSendView.as_view(), name='email-provider-test-send'),
    path('provider-webhooks/resend/<str:stream>', ProviderWebhookView.as_view(), name='email-resend-webhook'),
    path('stats', StatsView.as_view(), name='email-stats'),
    path('suppressions', SuppressionListView.as_view(), name='email-suppressions'),
    path('suppressions/<int:suppression_id>', SuppressionDetailView.as_view(), name='email-suppression-detail'),
    path('lanes/<str:lane>/<str:action>', LanePauseView.as_view(), name='email-lane-switch'),
    path('privacy/erase', PrivacyEraseView.as_view(), name='email-privacy-erase'),
    path('service-clients', ServiceClientListView.as_view(), name='email-service-clients'),
]
